########################################################################################
# ██████╗███╗   ███╗ ██████╗███╗   ██╗      ██████╗  █████╗ 
#██╔════╝████╗ ████║██╔════╝████╗  ██║      ╚════██╗██╔══██╗
#██║     ██╔████╔██║██║     ██╔██╗ ██║█████╗ █████╔╝╚█████╔╝
#██║     ██║╚██╔╝██║██║     ██║╚██╗██║╚════╝ ╚═══██╗██╔══██╗
#╚██████╗██║ ╚═╝ ██║╚██████╗██║ ╚████║      ██████╔╝╚█████╔╝
# ╚═════╝╚═╝     ╚═╝ ╚═════╝╚═╝  ╚═══╝      ╚═════╝  ╚════╝ 
########################################################################################                                        


# ____  _     ____  ____  ____  _  _____  _____ ___  _
#/  _ \/ \   /  _ \/   _\/  __\/ \/__ __\/__ __\\  \//
#| / \|| |   | / \||  /  |  \/|| |  / \    / \   \  / 
#| |-||| |_/\| |-|||  \_ |    /| |  | |    | |   / /  
#\_/ \|\____/\_/ \|\____/\_/\_\\_/  \_/    \_/  /_/   
#                                                     

# COLOURS
import = [
        "~/.config/alacritty/themes/catppuccin_mocha.toml"
]

# FONTS
[font]
# size = 14
size = 16

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# WINDOW
[window]

opacity = 0.9

[shell]
        program = "/run/current-system/sw/bin/tmux"
        args = ["new-session", "-A", "-D", "-s", "home"]
